#!/bin/bash
set -x
SELF=$(basename $0)
UPDATE_BASE=http://192.32.1.111:8000
KLMOVER_PATH=/opt/kaspersky/klnagent/bin/klmover
HOSTNAMEFILE=/etc/sysconfig/network

run_self_update() {
  echo "Performing self-update..."

  # Download new version
  echo -n "Downloading latest version..."
  if ! wget --quiet --output-document="$0.tmp" $UPDATE_BASE/$SELF ; then
    echo "Failed: Error while trying to wget new version!"
    echo "File requested: $UPDATE_BASE/$SELF"
    exit 1
  fi
  echo "Done."

  # Copy over modes from old version
  OCTAL_MODE=$(stat -c '%a' $SELF)
  if ! chmod $OCTAL_MODE "$0.tmp" ; then
    echo "Failed: Error while trying to set mode on $0.tmp."
    exit 1
  fi

  # Spawn update script
  cat > updateScript.sh << EOF
#!/bin/bash
# Overwrite old file with new
if mv "$0.tmp" "$0"; then
  echo "Done. Update complete."
  rm \$0
else
  echo "Failed!"
fi
EOF

  echo "Inserting update process..."
  exec /bin/bash updateScript.sh
}

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

ask() { 
  echo -n $1
  echo -n " [y/n]"
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo
  return $retval
}

show_menu() {
  clear
  echo "M E N U"
  echo
  echo
  echo "1) Rename host"
  echo "2) Regenerate HOSTID for klnagent"
  echo "3) Install CryptoPRO"
  echo "4) Install/reinstall licence for CryptoPRO"
  echo "5) Install keys"
  echo "6) Configure firefox"
  echo "0) Exit"
  echo
  echo -n ">>> "
}

rename_host(){
  if [ -f $HOSTNAMEFILE ] ; then
    if ask "RENAME HOST?"; then
      echo -n "Input new hostname: "
      read newhostname
      sed -e "s/^HOSTNAME=.*/HOSTNAME=$newhostname/" -i $HOSTNAMEFILE
    fi
  else
    echo "Hostname file $HOSTNAMEFILE not exist"
    sleep 3
  fi
}

change_klagent_hostid(){
  if [[ -x $KLMOVER_PATH ]]; then 
    if ask "REGENERATE HOSTID FOR KLNAGENT?"; then
      $KLMOVER_PATH -dupfix
    fi
  else 
    echo "Please install $KLMOVER_PATH"
    sleep 3
  fi
}

install_cryptopro(){
  apt-get update && apt-get -y install cryptopro-preinstall
  cd /tmp
  smbclient //server/000 -N -c 'prompt;recurse;cd Иванов\Distrib\sign_cont;mget "packets"'
  cd packets
  apt-get install *.rpm
  su - user -c '/opt/cprocsp/sbin/ia32/cpconfig -ini "\local\Software\Crypto Pro\CAdESplugin" -add multistring "TrustedSites" "http://192.168.101.102"'
}

install_cryptopro_license(){
  echo -n "Enter CryptoPro licence key in UPPER CASE with dashes (-) XXXX-XXXX-XXXX-XXXX: "
}

install_keys(){
  hdimage_dir=/var/opt/cprocsp/keys/user
  smb_service_name=//server/000
  cd /home/user
  curl -O http://sarmiac.medportal.saratov.gov.ru/media/uploads/admin/2016/01/19/guzmiac-ca.cer
  /opt/cprocsp/bin/ia32/certmgr -inst -file guzmiac-ca.cer -store uRoot
  if [[ ! -e $hdimage_dir ]]; then
    mkdir $hdimage_dir 
  fi
  cd $hdimage_dir 
  echo -n "Enter container directory names: "
  read container_dir_names
  for container_dir in $container_dir_names; do
      smbclient $smb_service_name -N -c "prompt;recurse;cd Иванов\Distrib\sign_cont;mget $container_dir"
  done
  /bin/chown -R user:user $hdimage_dir  
  su - user <<'EOF'
  for container_name in $(/opt/cprocsp/bin/ia32/csptest -keyset -enum_cont -fqcn -verifyc | egrep -o '\\\\.\\HDIMAGE\\RaUser(-[0-9,a-f]*)*'); do 
    /opt/cprocsp/bin/ia32/certmgr -inst -ask-cont -at_signature -cont $container_name
done
EOF
}

configure_firefox(){
  user_profile_path=/home/user/.mozilla/firefox
  user_profile_name=$(basename $user_profile_path/*.default)
  set_option(){
    sed -i 's/user_pref("'$1'",.*);/user_pref("'$1'",'$2');/' $user_profile_path/$user_profile_name/user.js
    grep -q $1 $user_profile_path/$user_profile_name/user.js || echo "user_pref(\"$1\",$2);" >> $user_profile_path/$user_profile_name/user.js
  }
#slashes need to be escaped
  set_option browser.search.defaultenginename '"Яндекс"'
  set_option browser.startup.homepage '"http:\/\/192.168.101.102\/mis\/\?use_cryptopro=true"'
  set_option plugin.state.libnpcades '2'
}

enable_vnc(){
  vncpasswd_file_name=passwd
  vncpasswd_file_dir=/root/.vnc
  cat > /etc/X11/xorg.conf.d/vnc.conf << EOF
  Section "Module"
    Load "vnc"
  EndSection

  Section "Screen"
    Identifier "VNC Extension"
    Option "SecurityTypes" "VncAuth"
    Option "UserPasswdVerifier" "VncAuth"
    Option "PasswordFile" "$vncpasswd_file_dir/$vncpasswd_file_name"
  EndSection
EOF
  if [[ ! -e $vncpasswd_file_dir/$vncpasswd_file_name ]]; then
    mkdir $vncpasswd_file_dir   
  fi
  echo 12345678 | vncpasswd -f > $vncpasswd_file_dir/$vncpasswd_file_name  
}

if [[ -z $1 ]]; then
  while show_menu; read -n 1 answ; do
    case $answ in
      1)
      rename_host
      sleep 5;;
      2)
      change_klagent_hostid
      sleep 5;;
      3)
      install_cryptopro
      sleep 5;;
      4)
      install_cryptopro_license
      sleep 5;;
      5)
      install_keys
      sleep 5;;
      6)
      configure_firefox
      sleep 5;;
      7)
      enable_vnc
      sleep 5;;
      0)
      exit 0;;
      q)
      exit 0;;
      *)
      echo "Wrong menu number";;
    esac
  done
else
  case $1 in
    full)
    rename_host
    change_klagent_hostid
    ;;
    *)
    echo "usage"
  esac
fi
